### ISSUE TITLE
编译的时候勾选了主题，实际生成的固件没有该主题

### ISSUE THREAD

**Issue by ihuaer** [thinktip/luci-theme-neobird#10]
make menuconfig #choose LUCI->Theme->Luci-theme-neobird  
插件列表选中了主题，但是实际编译出来的固件不带该主题

不知道怎么回事

清空源码重新编译会比较费时间，所有的文件需要重新下载过

**Comment by thinktip** [comment]
确保是最新的源码吗？前几天确实有问题，现在的应该不存在这个问题了啊

**Comment by ihuaer** [comment]
> 确保是最新的源码吗？前几天确实有问题，现在的应该不存在这个问题了啊

git pull最新的lean源码

手动安装你的主题Ipk是没问题的

源码里集成有点问题，菜单勾选了这个选项，实际编译出来没有该主题

下次我清空所有的缓存再试试

**Comment by ihuaer** [comment]
反馈：清空所有的源码和缓存后，可以集成该主题插件
