### ISSUE TITLE
1.97版 在EDGE上显示LAN 口和WAN 口还是会有位移

### ISSUE THREAD

**Issue by mitsukileung** [thinktip/luci-theme-neobird#11]
![无标题](https://user-images.githubusercontent.com/38887306/150775192-6b7962f3-1eb7-4db7-a35e-0a12c3f154d1.png)
在EDGE上显示LAN 口和WAN 口还是会有位移
手机端上显示只有WAN 口出现位移
大佬，主题好像不会自动转换白色和黑色，要怎样设置？

**Comment by thinktip** [comment]
你清一下缓存试试
主题是跟随浏览器设置的，你看看你的EDGE是不是设置了深色模式？

**Comment by Myoko** [comment]
![OP](https://user-images.githubusercontent.com/3013386/150902501-7d648dfd-f417-4bae-a2cf-5032472c8a43.png)

现在自动适配了！没有溢出了

**Comment by thinktip** [comment]
哈哈，你们都是主路由用OP啊
