### ISSUE TITLE
[需求] 添加「管控」的图标

### ISSUE THREAD

**Issue by loryncien** [thinktip/luci-theme-neobird#12]
**你好，有时间方便的话，麻烦能添加一下「管控」的图标吗**

![1](https://user-images.githubusercontent.com/9330590/150974867-52abaea8-fa23-4ae4-a814-5ad79784ce6a.png)
管控插件来源 [Lienol](https://github.com/Lienol/openwrt-package) 的luci-app-control-timewol、luci-app-control-webrestriction、luci-app-control-weburl等
右边主题来源：[jerrykuku/luci-theme-argon 18.06 v1.7.2](https://github.com/jerrykuku/luci-theme-argon/tree/cb52e4d07f07b22241ac4a32fc18420770dfb4d3)

**Comment by thinktip** [comment]
好的，这几天加上
