### ISSUE TITLE
主题截图很好看，目前看起来最舒服的样式，可惜了

### ISSUE THREAD

**Issue by sbwml** [thinktip/luci-theme-neobird#23]
不兼容最新的 Luci

**Comment by thinktip** [comment]
最新的Luci是指官方版本的Luci吗？
没研究过，有没有最新的Luci模板，我看一下有啥区别

**Comment by sbwml** [comment]
> 

我也说不清楚，就是OpenWRT官方的最新正式版：https://github.com/openwrt/openwrt/releases/tag/v21.02.2

[openwrt-21.02](https://github.com/openwrt/openwrt/tree/openwrt-21.02) 和 master  分支它两的主题的通用的，但是又不通用18 & 19 分支，你这个主题却是支持旧分支源码编译出来的openwrt  

有一说一，全网见到过的主题，就你这个最让人舒服。希望可以对openwrt正式分支做支持，或者给你提供个现成的 openwrt 操作界面和管理权限不知会不会很好就能适配。

**Comment by sbwml** [comment]
对于最新luci 的适配，不知道这条commit 有没有参考价值 https://github.com/openwrt/luci/commit/92eecedc8a52b0ba814daddb5167449a2ebb7f26


https://github.com/openwrt/luci/commits/openwrt-21.02/themes/luci-theme-material

**Comment by thinktip** [comment]
等有空了虚拟一个原版试一下，如果原版有meterial，那应该不麻烦，可能某些代码不支持的问题。

**Comment by sbwml** [comment]
> 等有空了虚拟一个原版试一下，如果原版有meterial，那应该不麻烦，可能某些代码不支持的问题。

是的   OpenWrt 也有meterial，期待大佬的佳作！

**Comment by RealFsh** [comment]
期待大佬适配最新的 Luci

**Comment by thinktip** [comment]
官方21.02可以用VSSR/SSRP之类的插件吗？可以的话我就直接用它了

**Comment by RealFsh** [comment]
> 官方21.02可以用VSSR/SSRP之类的插件吗？

可以的，我就在用
