### ISSUE TITLE
大佬新版本适配的怎么样啦？

### ISSUE THREAD

**Issue by sbwml** [thinktip/luci-theme-neobird#31]
等了2两月了。目前有没有预览版测试体验😀

新版本出来至少能抗两年，openwrt-22.03 能通用 openwrt-21.02 的所有主题

**Comment by RealFsh** [comment]
期待新版本

**Comment by sbwml** [comment]
> 期待新版本

我丢，看到小通知还以为作者回复有新版本体验了。。

**Comment by sbwml** [comment]
> 上去一个多月改了一个版本，差不多了，但很多地方不满意，细节调整起来比较麻烦，但一放下就懒得拾起来，哈哈，过几天看看。 自己不用，就没大有啥动力，哈哈

大佬  偷偷放个demo出来

**Comment by thinktip** [comment]
还没装插件测试，很多细节不完善。
![SCR-20220514-d1n](https://user-images.githubusercontent.com/16113429/168405931-8a216117-ff39-4fd8-a3b4-6b17fcfd47db.png)
![SCR-20220514-d1g](https://user-images.githubusercontent.com/16113429/168405933-9e353cb1-9eb9-4783-8906-5c03128ac599.png)
![SCR-20220514-d0j](https://user-images.githubusercontent.com/16113429/168405934-4eaea027-c045-4846-9115-44f17e92ec40.png)

**Comment by ten-ltw** [comment]
我这刚编译完 AC2100 的固件，刷上去碰到个问题，提示 `无效的用户名和/或密码！请重试。`，不知道 neobird 的前端登录的时候是不是 check 密码不能为空。

pull 的最新代码编译出来热乎的固件刷上去的。

因为以前都用的是 x86 虚拟机控制台直接修改密码再登录，这回蒙了。

[第一次登陆](https://openwrt.org/zh-cn/doc/howto/firstlogin) 按照国内的 doc telnet 被路由器拒绝访问了。

作者有没有一些提示呀。

**Comment by sbwml** [comment]
> 还没装插件测试，很多细节不完善。
> ![SCR-20220514-d1n](https://user-images.githubusercontent.com/16113429/168405931-8a216117-ff39-4fd8-a3b4-6b17fcfd47db.png)
> ![SCR-20220514-d1g](https://user-images.githubusercontent.com/16113429/168405933-9e353cb1-9eb9-4783-8906-5c03128ac599.png)
> ![SCR-20220514-d0j](https://user-images.githubusercontent.com/16113429/168405934-4eaea027-c045-4846-9115-44f17e92ec40.png)

我觉得已经很满意，求大佬发新分支

**Comment by HahahahaChen** [comment]
> 上去一个多月改了一个版本，差不多了，但很多地方不满意，细节调整起来比较麻烦，但一放下就懒得拾起来，哈哈，过几天看看。 自己不用，就没大有啥动力，哈哈

这个主题是真的漂亮，好期待适配官方源码
