### ISSUE TITLE
大佬，请问底栏图标指向的链接在哪里改呀？

### ISSUE THREAD

**Issue by Curious-r** [thinktip/luci-theme-neobird#33]
我的固件没编译SSR+，用的是passwall2，想让底栏的小飞机指向PASSWALL2，所以想请问下源码要在哪里修改这个链接

**Comment by zpengcom** [comment]
> 我的固件没编译SSR+，用的是passwall2，想让底栏的小飞机指向PASSWALL2，所以想请问下源码要在哪里修改这个链接

\usr\lib\lua\luci\view\themes\neobird\header.html
没找到图标在哪改。。

**Comment by Curious-r** [comment]
> > 我的固件没编译SSR+，用的是passwall2，想让底栏的小飞机指向PASSWALL2，所以想请问下源码要在哪里修改这个链接
> 
> \usr\lib\lua\luci\view\themes\neobird\header.html 没找到图标在哪改。。

  感谢指点，后边的目录好像写了图标的位置
`<a href="/cgi-bin/luci/admin/services/shadowsocksr"><img src="<%=media%>/images/ssr.png" /></a>`

**Comment by Curious-r** [comment]
> > 我的固件没编译SSR+，用的是passwall2，想让底栏的小飞机指向PASSWALL2，所以想请问下源码要在哪里修改这个链接
> 
> \usr\lib\lua\luci\view\themes\neobird\header.html 没找到图标在哪改。。

很奇怪，我fork之后修改了这里，但是编译出来还是原样

**Comment by Curious-r** [comment]
我知道为什么改了之后编译没效果了。。自行clone到工作目录之后，~~`make download`时又被feeds里的内容覆盖了。~~
修正：不是 `make download` 时被覆盖了，而是另一个feeds源里包含了这个包，实际上采用的不是手动clone的这个包，把修改过的包放在该源的路径下就可以了。

**Comment by miaoermua** [comment]
谢谢👍
